version: "3"
services:
    #PHP Service
    app-cabal:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app-cabal
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app-cabal
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-cabal-network

    #Nginx Service
    web-cabal:
        image: nginx:alpine
        container_name: web-cabal
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-cabal-network

#Docker Networks
networks:
    app-cabal-network:
        driver: bridge
